# Dockerfile_mageai
FROM mageai/mageai:latest

# Set working directory
WORKDIR /app

RUN apt-get update && apt-get install -y wget && \
    pip install -r requirements.txt && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Expose the default Mage AI port
EXPOSE 6789





